### ISSUE TITLE
AElf Playground - frontend

### ISSUE THREAD

**Issue by yongenaelf** [AElfProject/aelf-playground#3]
### Web

https://playground.test.aelf.dev

### Tasks
- [x] CI/CD for staging environment on k8s using GitHub Actions
- [x] aelf Hello World tutorial
- [x] aelf theme
- [x] aelf-sdk wallet integration
- [x] api mocking in dev server
- [x] integrate csharp intellisense
- [x] csharp language syntax highlighting support
- [x] protobuf language syntax highlighting support
